---
title: "Examples: v) Watsons Bay North, Lizard Island"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Examples: v) Watsons Bay North, Lizard Island}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Example `coralseed` scenario from Watsons North, an sheltered forereef site at Lizard Island (nGBR), December 2022. The model simulates a point source release of 1000 particles from a 5\*5m area within the site across a 6.95hrs period.

```{r mapoutput, fig.width=8, fig.height=8, fig.align = 'center', warning=FALSE, message=FALSE}

#devtools::install_github("marine-ecologist/coralseed",  lib = "/Users/rof011/coralseed")
devtools::document("/Users/rof011/coralseed")

library(coralseed)
library(ggplot2)
library(tidyverse)
library(sf)

seascape <- seascape_probability(reefoutline=reef_map, habitat=benthic_map)

particles <- seed_particles(input="example-watson", seascape=seascape,
                            limit_time=6.95, competency.function = "exponential", 
                            limit.time = 720, simulate.mortality = "typeI", 
                            simulate.mortality.n = 0.1, probability="additive",
                            return.plot=FALSE, silent=TRUE)

settlers <-  settle_particles(particles, probability="additive", silent=TRUE)
```

## testing with no frame

```{r}
map_output <- map_coralseed(seed_particles=particles, settle_particles=settlers, 
              seascape_probability=seascape, restoration.plot=c(100,100)) 

map_output



```

## testing in an iframe

```{r}

widgetframe::frameWidget(map_output, width = 750, height=750)

```