---
title: "Moore Reef (cGBR oceanparcels)"
author: "George Roff"
date: "2025-03-18"
format:
  html:
    toc: true
    math: mathjax
    code-fold: false
    code-tools: true
execute:
  echo: true
  warning: false
  message: false
editor: visual
---

```{r}
#| message: false
#| warning: false
#| cache: true
#| include: false
#| 
load(file="/Users/rof011/coralseed/data/infamis_tiles_exp.rda")

```

::: cell
```{=html}
<style>
  code, pre {
    font-size: 65%;
    color:darkgrey;
  }
</style>
```
:::

Simulated reseeding event at Moore Reef, central Great Barrier Reef based on ocean parcels input

# 1) seed particles

```{r}
#| echo: true
#| eval: true
#| message: false
#| warning: false
#| cache: true
#| fig-height: 5
#| fig-width: 9


library(coralseed)
library(ggplot2)
library(tidyverse)
library(sf)
library(tmap)

sf_use_s2(FALSE)

# load seascape  
moore_benthic_map <- system.file("extdata", "Moore_Benthic.geojson", package = "coralseed") |>
                              st_read(quiet=TRUE)

moore_reef_map <- system.file("extdata", "Moore_Geomorphic.geojson", package = "coralseed") |>
                              st_read(quiet=TRUE)

moore_seascape <- seascape_probability(reefoutline=moore_reef_map, habitat=moore_benthic_map)

# load particles - import example zarr (oceanparcels output)
moorereef_particles <- system.file("extdata", "output.zarr", package = "coralseed") |>  
                          import_zarr()

# run seed particles
moore_particles <- seed_particles(moorereef_particles,
                            set.centre = TRUE,
                            seascape = moore_seascape,
                            probability = "additive",
                            limit_time = 7,
                            competency.function = "exponential",
                            crs = 20353,
                            simulate.mortality = "typeII",
                            simulate.mortality.n = 0.1,
                            return.plot = TRUE,
                            return.summary = TRUE,
                            silent = FALSE)
                                  
```

# 2) settle particles

```{r}
#| message: false
#| warning: false
#| cache: true
#| fig-height: 8
#| fig-width: 9

moore_settlers <-  settle_particles(moore_particles,
                                    probability = "additive",
                                    silent = TRUE)

moore_settlement_density <- settlement_density(moore_settlers$points, cellsize=50)


```

# 3) map coralseed

```{r}
#| message: false
#| warning: false
#| eval: false

map_coralseed(seed_particles_input = moore_particles,
              settle_particles_input = moore_settlers,
              settlement_density_input = moore_settlement_density,
              seascape_probability = moore_seascape,
              restoration.plot = c(100,100),
              show.footprint = TRUE,
              show.tracks = TRUE,
              subsample = 1000,
              webGL = TRUE)

```

```{r}
#| message: false
#| warning: false
#| cache: true
#| fig-height: 10
#| fig-width: 12
#| eval: true
#| include: false

mooremap <- map_coralseed(seed_particles_input = moore_particles,
              settle_particles_input = moore_settlers,
              settlement_density_input = moore_settlement_density,
              seascape_probability = moore_seascape,
              restoration.plot = c(100,100),
              show.footprint = TRUE,
              show.tracks = TRUE,
              subsample = 1000,
              webGL = TRUE)


fs::dir_create(paste0(getwd(), "/vignettes/www"))
htmlwidgets::saveWidget(mooremap, paste0(getwd(), "/vignettes/www/mooremap.html"))
fs::dir_create(paste0(getwd(), "/docs/www"))
htmlwidgets::saveWidget(mooremap, paste0(getwd(), "/docs/www/mooremap.html"))
 


```

<iframe src="www/mooremap.html" width="100%" height="600" style="border:none;">

</iframe>

# 4) coralseed outputs

```{r}
#| message: false
#| warning: false
#| cache: true
#| fig-height: 9
#| fig-width: 12


flowchart_coralseed(seed_particles_input = moore_particles, 
                    settle_particles_input = moore_settlers, 
                    multiplier = 10000, 
                    postsettlement = 0.8)


```
