---
title: "Lizard Island (nGBR CONNIE)"
author: "George Roff"
date: "2025-03-18"
format:
  html:
    toc: true
    math: mathjax
    code-fold: false
    code-tools: true
execute:
  echo: true
  warning: false
  message: false
editor: visual
---

```{r}
#| message: false
#| warning: false
#| cache: true
#| include: false
#| 
load(file="/Users/rof011/coralseed/data/infamis_tiles_exp.rda")

```

::: cell
```{=html}
<style>
  code, pre {
    font-size: 65%;
    color:darkgrey;
  }
</style>
```
:::

Simulated reseeding event at Mermaid Bay, Lizard Island

# 1) seed particles

```{r}
#| eval: true
#| message: false
#| warning: false
#| include: true
#| cache: true
#| fig-height: 5
#| fig-width: 9

library(coralseed)
library(ggplot2)
library(tidyverse)
library(sf)
library(tmap)
  
sf_use_s2(FALSE)
  
# load seascape  
lizard_benthic_map <- system.file("extdata", "Lizard_Benthic.geojson", package = "coralseed") |>
                              st_read(quiet=TRUE)

lizard_reef_map <- system.file("extdata", "Lizard_Geomorphic.geojson", package = "coralseed") |>
                              st_read(quiet=TRUE)

lizard_seascape <- seascape_probability(reefoutline=lizard_reef_map, habitat=lizard_benthic_map)

# load particles
lizard_particles_sf <- system.file("extdata", "lizard_del_14_1512_sim1_10.json", package = "coralseed") |> st_read(quiet=TRUE)


# run seed particles
lizard_particles <- seed_particles(lizard_particles_sf,
                              zarr = FALSE,
                              set.centre = TRUE,
                              seascape = lizard_seascape,
                              probability = "additive",
                              limit.time = 12,
                              competency.function = "exponential",
                              crs = 20353,
                              simulate.mortality = "typeIII",
                              simulate.mortality.n = 0.1,
                              return.plot = TRUE,
                              return.summary = TRUE,
                              silent = FALSE)

```

# 2) settle particles

```{r}
#| message: false
#| warning: false
#| cache: true
#| fig-height: 8
#| fig-width: 9

lizard_settlers <- settle_particles(lizard_particles,
                                    probability = "additive",
                                    return.plot=FALSE,
                                    silent = TRUE)

plot_particles(lizard_settlers$points, lizard_seascape)

lizard_settlement_density <- settlement_density(lizard_settlers$points)
lizard_settlement_summary <- settlement_summary(lizard_particles, lizard_settlers, cellsize=50)

```

# 3) map coralseed

```{r}
#| message: false
#| warning: false
#| eval: false

map_coralseed(seed_particles_input = lizard_particles,
              settle_particles_input = lizard_settlers,
              settlement_density_input = lizard_settlement_density,
              seascape_probability = lizard_seascape,
              restoration.plot = c(100,100),
              show.footprint = TRUE,
              show.tracks = TRUE,
              subsample = 1000,
              webGL = TRUE)


```

```{r}
#| message: false
#| warning: false
#| cache: true
#| fig-height: 10
#| fig-width: 12
#| eval: true
#| include: false

lizardmap <- map_coralseed(seed_particles_input = lizard_particles,
              settle_particles_input = lizard_settlers,
              settlement_density_input = lizard_settlement_density,
              seascape_probability = lizard_seascape,
              restoration.plot = c(100,100),
              show.footprint = TRUE,
              show.tracks = TRUE,
              subsample = 1000,
              webGL = TRUE)

fs::dir_create("../vignettes/www")
htmlwidgets::saveWidget(lizardmap, "../vignettes/www/lizardmap.html")
fs::dir_create("../docs/www")
htmlwidgets::saveWidget(lizardmap, "../docs/www/lizardmap.html")
 


```

<iframe src="www/lizardmap.html" width="100%" height="600" style="border:none;">

</iframe>

# 4) coralseed outputs

```{r}
#| message: false
#| warning: false
#| cache: true
#| fig-height: 9
#| fig-width: 12

flowchart_coralseed(lizard_particles, lizard_settlers, multiplier=1000, postsettlement=0.8)


```
